export const LOGIN = 'LOGIN';

export const UPDATE_TEACHER = 'UPDATE_TEACHER';

export const OPEN_REVISING_ASSIGNMENT = 'OPEN_REVISING_ASSIGNMENT';

export const CLOSE_REVISING_ASSIGNMENT = 'CLOSE_REVISING_ASSIGNMENT';

export const REMOVE_ASSIGNMENT = 'REMOVE_ASSIGNMENT';
