export const LOGIN = 'LOGIN';

export const UPDATE_TEACHER = 'UPDATE_TEACHER';

export const OPEN_REVISING_ASSIGNMENT = 'OPEN_REVISING_ASSIGNMENT';

export const CLOSE_REVISING_ASSIGNMENT = 'CLOSE_REVISING_ASSIGNMENT';

export const REMOVE_ASSIGNMENT = 'REMOVE_ASSIGNMENT';

export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';

export const GET_TOKEN = 'GET_TOKEN';

export const LOGOUT = 'LOGOUT';

export const UPDATE_REVIEW = 'UPDATE_REVIEW';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';